[package]
name = "spire"
version = "0.1.0"
authors = ["Houtamelo"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.11.3"
rand = "0.8.5"
bounded-integer = { version = "0.5.7", features = ["std", "alloc", "macro", "types", "num-traits02", "zerocopy06", "step_trait"]}