[package]
name = "spire"
version = "0.1.0"
authors = ["Houtamelo"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.11.3"
rand = "0.8.5"
proc_macros = { path = "proc_macros" }
lazy_static = "1.4.0"
serde = { version = "1.0.180", features = ["derive"] }
ron = "0.8.1"
houta_utils = { package = "houtamelo_utils_gdnative", git = "https://github.com/Houtamelo/houtamelo_utils_gdnative.git" }
gdrust_export_nodepath = { package = "gdrust_export_node_path_macro", git = "https://github.com/Houtamelo/gdrust_export_node_path_macro.git" }
