[package]
name = "spire"
version = "0.1.0"
authors = ["Houtamelo"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.11"
rand = { version =  "0.8", features = ["serde1"] }
rand_xoshiro = { version = "0.6", features = ["serde1"] }
proc_macros = { path = "proc_macros" }
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
houta_utils = { version = "2.0.0", package = "houtamelo_utils", git = "https://github.com/Houtamelo/houtamelo_utils.git" }
houta_utils_gdnative = { package = "houtamelo_utils_gdnative", git = "https://github.com/Houtamelo/houtamelo_utils_gdnative.git" }
gdnative_export_node_as_path = "0.1"
getrandom = "0.2"
float-cmp = "0.9"
bracket-noise = "0.8.7"
comfy-bounded-ints = { version = "0.2", features = ["serde", "div_assign_zero"] }
parking_lot = "0.12"
uuid = { version = "1.7", features = ["serde"] }
