[package]
name = "spire"
version = "0.1.0"
authors = ["Houtamelo"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.11.3"
rand = "0.8.5"
proc_macros = { path = "proc_macros" }
lazy_static = "1.4.0"

