[package]
name = "proc_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.60", features = ["full"] }
proc-macro2 = { version = "1.0.82", features = ["nightly", "proc-macro"] }
quote = { version = "1.0.36", features = ["proc-macro"] }
